//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class PhotoWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Photo), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("startCut", startCut);
		L.RegFunction("CutImage", CutImage);
		L.RegFunction("SaveCutImg", SaveCutImg);
		L.RegFunction("getCutImgPath", getCutImgPath);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int startCut(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Photo obj = (Photo)ToLua.CheckObject<Photo>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.startCut(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CutImage(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Photo obj = (Photo)ToLua.CheckObject<Photo>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			System.Collections.IEnumerator o = obj.CutImage(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SaveCutImg(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Photo obj = (Photo)ToLua.CheckObject<Photo>(L, 1);
			obj.SaveCutImg();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getCutImgPath(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Photo obj = (Photo)ToLua.CheckObject<Photo>(L, 1);
			string o = obj.getCutImgPath();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

